lib/todo_web/router.ex
defmodule TodoWeb.Router do
  use TodoWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug TodoWeb.Plugs.CurrentUser

  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", TodoWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/signup", RegistrationController, only: [:new, :create]

    get "/signup", RegistrationController, :new

    resources "/signin", SessionController, only: [:new, :create]
    get "/signout", SessionController, :delete
    get "/signin", SessionController, :new
    get "/confirm", SessionController, :confirm
    get "/sign_out", SessionController, :delete

    resources "/todos", TodoController do
      resources "/items", ItemController, only: [:create]
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", TodoWeb do
  #   pipe_through :api
  # end
end

lib/todo_web/templates/page/index.html.eex
<div class="row">
  <div class="col-md-3">
    <h3>Todos</h3>
    <ul class="list-group">
    <%= for todo <- @todo do %> 
      <li class=""> <%= link todo.title, to: Routes.todo_path(@conn, :show, todo.id), class: "btn btn-link" %></li>
    <% end %>

    </ul>
  </div>
  <br>
  <div class="col-md-9">
    <div class="jumbotron">
      <div class="page-header text-center">
        <h2>Todo App</h2>
      </div>
      <div class="page-header text-center">
        <h2><strong>Choose the Todo Lists on the left to View</strong></h2>
        <h2><strong>or <a <%= link "Create", to: Routes.todo_path(@conn, :new), class: "btn btn-primary" %></a> a new one</strong></h2>
      </div>
    </div>
  </div>
</div>