lib/todo_web/router.ex
defmodule TodoWeb.Router do
  use TodoWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug TodoWeb.Plugs.CurrentUser

  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", TodoWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/signup", RegistrationController, only: [:new, :create]

    get "/signup", RegistrationController, :new

    resources "/signin", SessionController, only: [:new, :create]
    get "/signout", SessionController, :delete
    get "/signin", SessionController, :new
    get "/confirm", SessionController, :confirm
    get "/sign_out", SessionController, :delete

    resources "/todos", TodoController do
      resources "/items", ItemController, only: [:create]
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", TodoWeb do
  #   pipe_through :api
  # end
end

lib/todo_web/views/layout_view.ex
defmodule TodoWeb.LayoutView do
  use TodoWeb, :view
end

lib/todo_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Todo </title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">  </head>

  </head>
  <body>
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 bg-white border-bottom box-shadow">
      <h5 class="my-0 mr-md-auto font-weight-normal">
        <a href="/" class="navbar-brand text-dark"><strong>Todo App</strong></a>
      </h5>
        <%= if Todo.Auth.user_signed_in?(@conn) do %>
          <nav class="my-2 my-md-0 mr-md-3">
            Signed in as: <strong><%= @current_user.email %></strong>
          </nav>
          <a class="btn btn-primary" href="<%= Routes.session_path(@conn, :delete) %>">Sign Out</a> 
        <% else %>
          <a class="btn btn-primary" href="<%= Routes.session_path(@conn, :new) %>">Sign In</a> &nbsp
          <a class="btn btn-danger" href="<%= Routes.registration_path(@conn, :new) %>">Sign up</a>
        <% end %>
    </div>
    <main role="main" class="container">
      <%= if get_flash(@conn, :info) do %>
        <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <% end %>
      <%= if get_flash(@conn, :error) do %>
        <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <% end %>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>  </body>

  </body>
</html>